### ISSUE TITLE
Allow critical for connection refused

### ISSUE THREAD

**Issue by HOSTED-POWER** [vint21h/nagios-check-supervisord#5]
Hi,

Although we can patch it, we would love an option to return state critical when the connection is refused or timed out:

```
check_supervisord.py -s 127.0.0.1 -p 9001
ERROR: Server communication problem. [Errno 111] Connection refused
echo $?
3
```

Would be great if it was 2 instead of 3.

Unknown is not bad enough for us, on critical we take special actions, that is why. We saw other nagios checks supplying similar functionality trough a parameter.

**Comment by vint21h** [comment]
```
/check_supervisord.py -s 127.0.0.1 -p 9001 --network-errors-exit-code='critical'
ERROR: Server communication problem. [Errno 111] Connection refused
echo $?
2
```
```
/check_supervisord.py -s 127.0.0.1 -p 9001 --network-errors-exit-code='unknown'
ERROR: Server communication problem. [Errno 111] Connection refused
echo $?
3
```

Enjoy using the last version.
