### ISSUE TITLE
Option for exit status when no programs found

### ISSUE THREAD

**Issue by prupert** [vint21h/nagios-check-supervisord#8]
If no supervisord programs are defined, currently the script will exit with the UNKOWN exit code. I believe it may be useful to set the desired --no-progams-defined-status via an argument. In some cases it may be desirable to raise a WARNING or CRITICAL, in other cases it may be expected and thus should result in OK state.

**Comment by vint21h** [comment]
Good idea, more configurability is always a great thing, but there is one moment to clarify - what a reason to change the default behavior, it is about returning OK status at no programs found case.

**Comment by prupert** [comment]
I think the current behaviour of UNKNOWN seems in line with expectations. For my specific use case I would set OK as default, but I won't dare to speak for others. :-)

**Comment by vint21h** [comment]
Try https://github.com/vint21h/nagios-check-supervisord/releases/tag/2.0.0
There is a new command-line argument "--no-programs-defined-exit-code" for your purpose with available variants: ok, warning, critical, unknown
